export const transformers = [
  {
    id: 'TR-001',
    name: 'Bandra Substation',
    location: 'Mumbai, MH',
    status: 'Operational',
    criticality: 'High',
    last_inspection: '2023-10-15',
    manufacturer: 'Bharat Heavy Electricals',
    servicedBy: 'Ravi Kumar',
    load: 75,
    nextServiceDate: '2024-10-15',
  },
  {
    id: 'TR-002',
    name: 'Cyber City Substation',
    location: 'Gurgaon, HR',
    status: 'Needs Attention',
    criticality: 'High',
    last_inspection: '2024-05-20',
    manufacturer: 'Siemens India',
    servicedBy: 'Priya Sharma',
    load: 85,
    nextServiceDate: '2024-11-20',
  },
  {
    id: 'TR-003',
    name: 'Koramangala Substation',
    location: 'Bengaluru, KA',
    status: 'Operational',
    criticality: 'Medium',
    last_inspection: '2024-02-01',
    manufacturer: 'ABB India',
    servicedBy: 'Anil Singh',
    load: 60,
    nextServiceDate: '2025-02-01',
  },
  {
    id: 'TR-004',
    name: 'T. Nagar Power Grid',
    location: 'Chennai, TN',
    status: 'Under Maintenance',
    criticality: 'Medium',
    last_inspection: '2024-06-10',
    manufacturer: 'Crompton Greaves',
    servicedBy: 'Meena Iyer',
    load: 55,
    nextServiceDate: '2024-12-10',
  },
  {
    id: 'TR-005',
    name: 'Salt Lake Sector V',
    location: 'Kolkata, WB',
    status: 'Operational',
    criticality: 'Low',
    last_inspection: '2023-11-05',
    manufacturer: 'Bharat Heavy Electricals',
    servicedBy: 'Sanjay Das',
    load: 40,
    nextServiceDate: '2024-11-05',
  },
];

export const dashboardStats = {
  monitored: 12,
  alerts: 3,
  operational: 9,
  health: 92,
};

export const faultDistributionData = [
  { name: 'Axial Displacement', value: 8, fill: 'var(--color-chart-1)' },
  { name: 'Winding Deformation', value: 5, fill: 'var(--color-chart-2)' },
  { name: 'Core Faults', value: 3, fill: 'var(--color-chart-3)' },
  { name: 'Bushing Faults', value: 2, fill: 'var(--color-chart-4)' },
  { name: 'Other', value: 4, fill: 'var(--color-chart-5)' },
];

export const analysisTrendData = [
  { date: 'Jan', Analyses: 30, Alerts: 5 },
  { date: 'Feb', Analyses: 45, Alerts: 8 },
  { date: 'Mar', Analyses: 60, Alerts: 12 },
  { date: 'Apr', Analyses: 50, Alerts: 7 },
  { date: 'May', Analyses: 70, Alerts: 10 },
  { date: 'Jun', Analyses: 85, Alerts: 15 },
];
